PACKAGE="libatasmart"
VER="0.19"

DEPENDS=(   eudev glibc  )
CONFLICTS=()

URL="http://0pointer.de/public/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS --disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
