PACKAGE="xf86-video-amdgpu"
VER="19.1.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 AMD GPU Driver"

DEPENDS=(expat libdrm libpciaccess mesa xorgproto)
CONFLICTS=()

LAUNCHDIR="$(pwd)"
URL="https://x.org/releases/individual/driver/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    patch -p1 < $LAUNCHDIR/patches/rootless-amdgpu.patch
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
