PACKAGE="xf86-video-amdgpu"
VER="21.0.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 AMD GPU Driver"

DEPENDS=( expat libdrm libpciaccess mesa xorgproto eudev glibc   )
CONFLICTS=()

LAUNCHDIR="$(pwd)"
URL="https://x.org/releases/individual/driver/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    patch -p1 < $LAUNCHDIR/patches/rootless-amdgpu.patch
    patch -p1 < $LAUNCHDIR/patches/link-failure.patch
	./configure $CONFIGUREOPTS --enable-glamor --enable-dri3
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
