PACKAGE="libunwind"
VER="1.5.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Library to define a portable and efficient C API"

DEPENDS=( gcc glibc xz zlib   )
CONFLICTS=()

URL="https://github.com/libunwind/libunwind/releases/download/v1.5/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
