PACKAGE="xorg-server"
VER="1.20.13"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( fontconfig bzip2 freetype-harfbuzz libX11 libXau libXdamage libXext libXfixes libXfont2 libXxf86vm libdrm libepoxy libfontenc libpciaccess openssl libxcb libxkbfile libxshmfence mesa pixman xkeyboard-config zlib brotli graphite2 libunwind eudev glibc libXdmcp libbsd  wayland  )
CONFLICTS=()

DESCRIPTION="X11 Server"

LAUNCHDIR="$(pwd)"
URL="https://x.org/releases/individual/xserver/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    	patch -p1 < $LAUNCHDIR/patches/rootless_modesetting.patch
	patch -p1 < $LAUNCHDIR/patches/fix-crash.patch
	./configure $CONFIGUREOPTS \
	--localstatedir=/var \
	--disable-systemd-logind \
	--enable-xwayland \
	--disable-unit-tests \
	--enable-glx \
	--enable-dri \
	--enable-dri2 \
	--enable-dri3 \
	--enable-glamor \
	--enable-xorg \
	--with-sha1=libcrypto \
	--with-systemd-daemon=off
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
