PACKAGE="gst-plugins-good"
VER="1.18.4"

DEPENDS=(   cairo flac gcc gdk-pixbuf glib glibc gst-plugins-base gstreamer gtk3 lame libgudev libjpeg-turbo libpng libsoup libvpx libX11 libXdamage libXext libXfixes pulseaudio taglib zlib  )
CONFLICTS=()

URL="https://gstreamer.freedesktop.org/src/${PACKAGE}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	mkdir build
	cd build
	export DESTDIR="$DEST"
	meson --prefix=/usr -Dbuildtype=release ..
	cd ..
}
__compilesrc(){
	cd build
	ninja
	cd ..
}
__installsrc(){
	cd build
	ninja install
}
