PACKAGE="acl"
VER="2.2.53"
CRYPT="key"

DESCRIPTION="Access Control Lists"

ARCH="installer"
ACCESS="restricted"

DEPENDS=(attr)
CONFLICTS=()

URL="http://download.savannah.gnu.org/releases/acl/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"
__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xvzf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS 
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
