PACKAGE="libpsl"
VER="0.21.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Library for handling Public Suffix List"

DEPENDS=(libidn2 libunistring)
CONFLICTS=()

URL="https://github.com/rockdaboot/libpsl/releases/download/${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
