PACKAGE="audit"
VER="3.0.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Security audit"

DEPENDS=(   glibc libcap-ng  )
CONFLICTS=()

#URL="https://github.com/linux-audit/audit-userspace/releases/download/v${VER}/"
SRCDIR="audit-userspace-${VER}"
SRCTGZ="v${VER}.tar.gz"
SRCURL="https://github.com/linux-audit/audit-userspace/archive/v${VER}.tar.gz"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
./autogen.sh    
./configure $CONFIGUREOPTS --disable-remote --disable-zos-remote --without-python --without-python3
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
GITHUB_CHECK=1
