PACKAGE="audit"
VER="2.8.5"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Security audit"

DEPENDS=()
CONFLICTS=()

#URL="https://github.com/linux-audit/audit-userspace/releases/download/v${VER}/"
SRCDIR="audit-userspace-${VER}"
SRCTGZ="v${VER}.tar.gz"
SRCURL="https://github.com/linux-audit/audit-userspace/archive/v${VER}.tar.gz"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
./autogen.sh    
./configure $CONFIGUREOPTS --disable-remote
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
