PACKAGE="groff"
VER="1.22.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="GNU Typesetting system"

DEPENDS=( perl gcc glibc   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/groff/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
