PACKAGE="xinput"
VER="1.6.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( libX11 libXmu libXi libXinerama glibc libXext libXrandr   )
CONFLICTS=()

DESCRIPTION="X11 Input"

URL="https://x.org/releases/individual/app/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--mandir=/usr/share/man \
	--localstatedir=/var 

}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
