PACKAGE="xz"
VER="5.2.5"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( bash glibc   )
CONFLICTS=()

URL="https://tukaani.org/xz/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
