PACKAGE="libsasl"
VER="2.1.27"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Simple authorization and security layer library"

DEPENDS=( openssl gdbm glibc krb5 libxcrypt linux-pam pam   )
CONFLICTS=()

URL="https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-${VER}/"
SRCDIR="cyrus-sasl-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
