PACKAGE="libxkbcommon"
VER="1.3.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 KeyBoarD"

DEPENDS=( glibc libxcb  wayland  )
CONFLICTS=()

URL="https://xkbcommon.org/download/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    export DESTDIR="$DEST"
    meson \
	--prefix=/usr \
	-Denable-wayland=true \
	-Denable-docs=false \
	-Denable-xkbregistry=false \
	. output
}
__compilesrc(){
    ninja -C output
}
__installsrc(){
    ninja -C output install
}
