PACKAGE="check"
VER="0.15.2"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DEPENDS=(gawk)
CONFLICTS=()

URL="https://github.com/libcheck/check/releases/download/${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"
__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	tar xzf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
