PACKAGE="inetutils"
VER="2.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Networking utilities"

DEPENDS=( libcap glibc libxcrypt ncurses readline   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/inetutils/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS 
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
