PACKAGE="m4"
VER="1.4.19"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="GNU m4 preprocessor"

DEPENDS=( bash glibc   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/m4/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
