PACKAGE="xcb-util-wm"
VER="0.4.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(libxcb)
CONFLICTS=()

DESCRIPTION="XCB WM "

URL="https://xcb.freedesktop.org/dist/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
