PACKAGE="less"
VER="590"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Long output pager"

DEPENDS=( glibc ncurses   )
CONFLICTS=()

URL="http://www.greenwoodsoftware.com/less/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c  $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
