PACKAGE="libgcrypt"
VER="1.9.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="General-purpose cryptographic library based on gnupg code"

DEPENDS=(libgpg-error)
CONFLICTS=()

URL="https://www.gnupg.org/ftp/gcrypt/libgcrypt/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
