PACKAGE="gobject-introspection"
VER="1.66.1"

DEPENDS=(   glib glibc libffi  )
CONFLICTS=()

URL="https://download.gnome.org/sources/${PACKAGE}/1.66/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	mkdir build
	cd build
	export DESTDIR="$DEST"
	meson --prefix=/usr ..
	cd ..

}
__compilesrc(){
	cd build
 	ninja
	cd ..
}
__installsrc(){
	cd build
	ninja install
	cd ..
}
