PACKAGE="xcb-util-cursor"
VER="0.1.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(xcb-util xcb-util-image xcb-util-renderutil libxcb libXau)
CONFLICTS=()

URL="https://xcb.freedesktop.org/dist/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--disable-static
}
__compilesrc(){
    make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
