PACKAGE="kbd"
VER="2.3.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="KeyBoarD"

DEPENDS=(glibc)
CONFLICTS=()

URL="https://www.kernel.org/pub/linux/utils/kbd/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--disable-vlock
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
