PACKAGE="man-db"
VER="2.9.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Manual page viewer"

DEPENDS=( bash gdbm zlib groff libpipeline less glibc libseccomp   )
CONFLICTS=()

URL=" http://download.savannah.gnu.org/releases/man-db/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--disable-setuid	\
	--enable-cache-owner=bin	\
	--with-browser=/usr/bin/lynx	\
	--with-vgrind=/usr/bin/vgrind	\
	--with-grap=/usr/bin/grap	\
	--with-systemdtmpfilesdir=	\
	--with-systemdsystemunitdir=

}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install --ignore-errors
}
