PACKAGE="polkit"
VER="0.120"

DEPENDS=(   elogind expat gcc glib glibc linux-pam pam  )
CONFLICTS=()

URL="https://www.freedesktop.org/software/polkit/releases/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"
PATCHDIR="$(pwd)/patches"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	patch -Np1 -i ${PATCHDIR}/polkit-0.118-fix_elogind_detection-1.patch &&
	autoreconf -fv &&
    ./configure $CONFIGUREOPTS --localstatedir=/var --disable-static --disable-libsystemd-login
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install &&
	mkdir -pv $DEST/etc/pam.d	&&
cat > $DEST/etc/pam.d/polkit-1 << "EOF"
# Begin /etc/pam.d/polkit-1

auth     include        system-auth
account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/polkit-1
EOF
}

pkg_preinstall(){
	groupadd -fg 27 polkitd &&
useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
        -g polkitd -s /bin/false polkitd
}
