PACKAGE="libffi"
VER="3.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Foreign Function Interface library"

DEPENDS=( glibc   )
CONFLICTS=()

URL="ftp://sourceware.org/pub/libffi/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
