PACKAGE="libva"
VER="2.11.0"

DEPENDS=( glibc libdrm libX11 libXext libXfixes mesa  wayland  )
CONFLICTS=()

URL="https://github.com/intel/libva/releases/download/${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=y
