PACKAGE="libmnl"
VER="1.0.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Minimalistic NetLink library"

DEPENDS=( glibc   )
CONFLICTS=()

URL="https://netfilter.org/projects/libmnl/files/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
