PACKAGE="libogg"
VER="1.3.5"

DEPENDS=(   glibc  )
CONFLICTS=()

URL="https://downloads.xiph.org/releases/ogg/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS --disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
