PACKAGE="xf86-video-intel"
VER="846b53dacd96981329bcb9ef348e6acba0b53e94"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( libXScrnSaver libXcursor libXinerama libXrandr libXtst xorg-server eudev glibc libX11 libXdamage libXext libXfixes libXrender libdrm libpciaccess pixman   )
CONFLICTS=()

DESCRIPTION="X11 Intel GPU Driver"

URL="https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/archive/${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
	export DESTDIR="$DEST"
	export LDFLAGS="-Wl,-z,lazy"
		enable globstar
#	sed -i -e 's/slave_dst/secondary_dst/g' -e 's/current_master/current_primary/g' -e 's/master_pixmap/primary_pixmap/g' */*.c */*.h */*/*.h */*/*.c
	meson \
	--prefix=/usr \
	--libexecdir=/usr/lib \
	-Ddefault-dri=3 \
	-Dxvmc=false \
	-Dvalgrind=false \
	. build
}
__compilesrc(){
	ninja -C build
}
__installsrc(){
	ninja -C build install
}
