PACKAGE="gettext"
VER="0.21"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(gcc acl bash)
CONFLICTS=()

DESCRIPTION="GNU Localization library"

URL="http://ftp.gnu.org/gnu/gettext/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
