PACKAGE="libidn2"
VER="2.3.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Library for working with IDN"

DEPENDS=(libunistring)
CONFLICTS=()

URL="https://ftp.gnu.org/gnu/libidn/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
