PACKAGE="xf86-video-nouveau"
VER="1.0.17"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( libdrm xorgproto eudev glibc   )
CONFLICTS=()

DESCRIPTION="X11 Nvidia GPU Driver"

LAUNCHDIR="$(pwd)"
URL="https://x.org/releases/individual/driver/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    	patch -p1 < $LAUNCHDIR/patches/rootless-nouveau.patch
	export LDFLAGS="-Wl,-z,lazy"
	enable globstar
#	sed -i -e 's/slave_dst/secondary_dst/g' -e 's/current_master/current_primary/g' -e 's/master_pixmap/primary_pixmap/g' */*.c */*.h
	./configure $CONFIGUREOPTS --enable-glamor --enable-dri3
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}

