PACKAGE="automake"
VER="1.16.2"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(perl bash)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/automake/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	 tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
