PACKAGE="xfce4-settings"
VER="4.16.2"

DEPENDS=(   atk cairo exo fontconfig garcon gdk-pixbuf glib glibc gtk3 libnotify libX11 libXcursor libxfce4ui libxfce4util libXi libxklavier libXrandr pango xfconf  )
CONFLICTS=()

URL="http://archive.xfce.org/src/xfce/xfce4-settings/4.16/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
