PACKAGE="vim"
VER="8.2.3001"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

CONFLICTS=()
DEPENDS=( gmp glibc zlib libffi acl ncurses   )

DESCRIPTION="VI Improved text editor"

URL="http://anduin.linuxfromscratch.org/LFS/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
	cd src
    ./configure $CONFIGUREOPTS \
	--with-features=large  \
	--disable-gui \
	--with-x=no
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
    cd ..
}
