PACKAGE="dejagnu"
VER="1.6.2"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DESCRIPTION="Test suite"

DEPENDS=(bash expect)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/dejagnu/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xzf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install --keep-going --ignore-errors
}
