PACKAGE="gstreamer"
VER="1.19.2"

DEPENDS=(   elfutils glib glibc libcap libunwind  )
CONFLICTS=()

URL="https://gstreamer.freedesktop.org/src/gstreamer/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	mkdir build
	cd build
	export DESTDIR="$DEST"
	meson --prefix=/usr -Dbuildtype=release -Dgst_debug=false ..
	cd ..
}
__compilesrc(){
	cd build
	ninja
	cd ..
}
__installsrc(){
	cd build
	ninja install
}
