PACKAGE="gtksourceview"
VER="3.24.11"

DEPENDS=(   atk cairo freetype-harfbuzz gdk-pixbuf glib glibc gtk3 libxml2 pango  )
CONFLICTS=()

URL="https://download.gnome.org/sources/gtksourceview/3.24/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}

