PACKAGE="xev"
VER="1.2.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(libX11 libXrandr)
CONFLICTS=()

URL="https://xorg.freedesktop.org/archive/individual/app/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
