PACKAGE="libunistring"
VER="0.9.10"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Unicode string library"

DEPENDS=(glibc)
CONFLICTS=()

URL="https://ftp.gnu.org/gnu/libunistring/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
