PACKAGE="freetype-harfbuzz"
VER="2.10.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="freetype and harfbuzz font aliasing libraries"

DEPENDS=( bzip2 expat glib libX11 libXau libXdamage libXext libXfixes libXrender libXxf86vm libdrm libpng libxcb libxshmfence mesa pixman zlib brotli glibc gcc  cairo graphite2 icu  )
CONFLICTS=()

URL="https://download-mirror.savannah.gnu.org/releases/freetype/"
SRCDIR="${PACKAGE%-harfbuzz}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
    wget -c "https://github.com/harfbuzz/harfbuzz/archive/2.7.2.tar.gz" # harfbuzz
}
__unpacksrc(){
    tar xJf $SRCTGZ
    tar xzf 2.7.2.tar.gz -C "$SRCDIR"/
    mv "$SRCDIR"/harfbuzz-2.7.2 "$SRCDIR"/harfbuzz
}
__preparesrc(){
	
   CFLAGS="$CFLAGS -DDEFAULT_TT_INTERPRETER_VERSION=TT_INTERPRETER_VERSION_40" ./configure $CONFIGUREOPTS \
	--enable-freetype-config \
	--with-harfbuzz="no"
   make $MAKEOPTS
   make $MAKEOPTS DESTDIR="$DEST" install
   cd harfbuzz
   export DESTDIR="$DEST"
   export CFLAGS="$CFLAGS -I$DEST/usr/include/freetype2"
   export CXXFLAGS="$CXXFLAGS -I$DEST/usr/include/freetype2"
   export LDFLAGS="$LDFLAGS -L$DEST/usr/lib"
   	mkdir build
	cd build
	meson \
	--prefix=/usr \
	-Dpkg_config_path="$DEST/usr/lib/pkgconfig" \
	-Ddefault_library=both \
	-Dglib=enabled \
	-Dfreetype=enabled \
	-Dcairo=enabled \
	-Dgraphite=enabled \
	-Dicu=enabled \
	-Dbenchmark=disabled \
	-Dtest=disabled \
	.. 
   ninja 
   ninja  install
   cd ../..
   export HARFBUZZ_CFLAGS="-I$PWD/harfbuzz/src"
   export HARFBUZZ_LIBS="-L$PWD/harfbuzz/output/src -lharfbuzz"
   CFLAGS="$CFLAGS -DDEFAULT_TT_INTERPRETER_VERSION=TT_INTERPRETER_VERSION_40" ./configure $CONFIGUREOPTS \
	--enable-freetype-config \
	--with-harfbuzz="yes"
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
	cd harfbuzz/build	
ninja  install
}
GITHUB_CHECK=1
