PACKAGE="mpc"
VER="1.2.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( glibc mpfr gmp   )
CONFLICTS=()

DESCRIPTION="MultiPrecession"

URL="https://ftp.gnu.org/gnu/mpc/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
