PACKAGE="mpc"
VER="1.1.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(glibc mpfr)
CONFLICTS=()

URL="https://ftp.gnu.org/gnu/mpc/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
