PACKAGE="grep"
VER="3.6"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Grab Regular Expressions and Print em"

DEPENDS=(glibc)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/grep/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
