PACKAGE="gnome-themes-extra"
VER="3.28"

DEPENDS=(   atk cairo fontconfig freetype-harfbuzz gdk-pixbuf glib glibc gtk2 pango  )
CONFLICTS=()

URL="https://download.gnome.org/sources/gnome-themes-extra/${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS 
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
