PACKAGE="xcb-util-renderutil"
VER="0.3.9"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( libXau libxcb glibc   )
CONFLICTS=()

DESCRIPTION="XCB RenderUtil"

URL="https://xcb.freedesktop.org/dist/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
