PACKAGE="bc"
VER="3.1.5"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DEPENDS=(readline)
CONFLICTS=()

SRCURL="https://git.yzena.com/gavin/bc.git"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	tar xJF $SRCTGZ
}
__preparesrc(){
	./configure --prefix=/usr
}
__compilesrc(){
	make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install 
}
