PACKAGE="xml-parser"
VER="2.46"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(expat)
CONFLICTS=()

DESCRIPTION="Perl XML Parser"

URL="https://cpan.metacpan.org/authors/id/T/TO/TODDR/"
SRCDIR="XML-Parser-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    #./configure $CONFIGUREOPTS
    perl Makefile.PL
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
