PACKAGE="texinfo"
VER="6.8"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( ncurses gzip perl bash glibc   )
CONFLICTS=()

DESCRIPTION="Documentation viewer"

URL="http://ftp.gnu.org/gnu/texinfo/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
	sed -e 's/__attribute_nonnull__/__nonnull/' \
    -i gnulib/lib/malloc/dynarray-skeleton.c
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
