PACKAGE="util-linux"
VER="2.37.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( coreutils shadow libcap eudev file glibc libxcrypt ncurses pcre2 zlib   )
CONFLICTS=()

DESCRIPTION="Non-gnu coreutils"

URL="https://www.kernel.org/pub/linux/utils/util-linux/v2.37/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python	\
	    --without-systemd	\
	    --without-systemdsystemunitdir
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install --ignore-errors
}
