PACKAGE="libpipeline"
VER="1.5.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Pipeline manipulation library"

DEPENDS=( glibc   )
CONFLICTS=()

URL="http://download.savannah.gnu.org/releases/libpipeline/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
