PACKAGE="parole"
VER="4.16.0"

DEPENDS=(   atk cairo dbus dbus-glib freetype-harfbuzz gdk-pixbuf glib glibc gst-plugins-base gstreamer gtk3 libICE libnotify libSM libX11 libxfce4ui libxfce4util pango taglib xfconf  )
CONFLICTS=()

URL="http://archive.xfce.org/src/apps/${PACKAGE}/4.16/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
