#!/bin/bash
PACKAGE="libtasn1"
VER="4.17.0"

DEPENDS=( glibc   )
CONFLICTS=()

URL="https://ftp.gnu.org/gnu/libtasn1/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}

__unpacksrc(){
	tar xf $SRCTGZ
}

__preparesrc(){
	./configure --prefix=/usr --disable-static
}

__compilesrc(){
	make $MAKEOPTS
}

__installsrc(){
	make install DESTDIR="$DEST"
}


