PACKAGE="pinentry"
VER="1.2.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Collection of password dialogs"

DEPENDS=( libassuan libgpg-error glibc libcap ncurses  atk cairo fontconfig freetype-harfbuzz gcr gdk-pixbuf glib gtk2 gtk3 libsecret p11-kit pango  )
CONFLICTS=()

URL="https://www.gnupg.org/ftp/gcrypt/pinentry/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
