PACKAGE="libXinerama"
VER="1.1.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 MultiScreen extension"

DEPENDS=( libXext xorgproto glibc libX11   )
CONFLICTS=()

URL="https://x.org/releases/individual/lib/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--enable-malloc0returnsnull
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
