PACKAGE="linux-pam"
VER="1.5.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( audit glibc libnsl libtirpc libxcrypt  pam  )
CONFLICTS=()

DESCRIPTION="Pluggable Authentication Modules"

URL="https://github.com/linux-pam/linux-pam/releases/download/v${VER}/"
SRCDIR="Linux-PAM-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    sed -e /service_DATA/d \
    	-i modules/pam_namespace/Makefile.am &&
    autoreconf
    ./configure $CONFIGUREOPTS \
	--libdir=/usr/lib \
	--enable-securedir=/lib/security --with-db-uniquename
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
	chmod -v 4755 $DEST/sbin/unix_chkpwd 
	mkdir -pv $DEST/usr/lib $DEST/lib $DEST/etc/pam.d
	for file in pam pam_misc pamc
	do
	  mv -v $DEST/usr/lib/lib${file}.so.* $DEST/lib
	  ln -sfv ../../lib/$(readlink $DEST/usr/lib/lib${file}.so) $DEST/usr/lib/lib${file}.so
	done
install -vdm755 $DEST/etc/pam.d 
cat > $DEST/etc/pam.d/system-account << "EOF" 
# Begin /etc/pam.d/system-account

account   required    pam_unix.so

# End /etc/pam.d/system-account
EOF

cat > $DEST/etc/pam.d/system-auth << "EOF" 
# Begin /etc/pam.d/system-auth

auth      required    pam_unix.so

# End /etc/pam.d/system-auth
EOF

cat > $DEST/etc/pam.d/system-session << "EOF"
# Begin /etc/pam.d/system-session

session   required    pam_unix.so

# End /etc/pam.d/system-session
EOF
cat > $DEST/etc/pam.d/system-password << "EOF"
# Begin /etc/pam.d/system-password

# use sha512 hash for encryption, use shadow, and try to use any previously
# defined authentication token (chosen password) set by any prior module
password  required    pam_unix.so       sha512 shadow try_first_pass

# End /etc/pam.d/system-password
EOF
cat > $DEST/etc/pam.d/other << "EOF"
# Begin /etc/pam.d/other

auth        required        pam_warn.so
auth        required        pam_deny.so
account     required        pam_warn.so
account     required        pam_deny.so
password    required        pam_warn.so
password    required        pam_deny.so
session     required        pam_warn.so
session     required        pam_deny.so

# End /etc/pam.d/other
EOF
}
