PACKAGE="intltool"
VER="0.51.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(perl xml-parser)
CONFLICTS=()

URL="https://launchpad.net/intltool/trunk/${VER}/+download/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
