PACKAGE="gnumeric"
VER="1.12.50"

DEPENDS=(   atk cairo freetype-harfbuzz gdk-pixbuf glib glibc goffice gtk3 libgsf libxml2 pango zlib  )
CONFLICTS=()

URL="https://download.gnome.org/sources/gnumeric/1.12/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS --without-perl --disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}

