PACKAGE="libtool"
VER="2.4.6"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Part of GNU Autotools"

DEPENDS=( bash tar glibc   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/libtool/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
