PACKAGE="xf86-video-ati"
VER="19.1.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(expat libdrm libpciaccess mesa xorgproto)
CONFLICTS=()

DESCRIPTION="X11 ATI GPU Driver"

LAUNCHDIR="$(pwd)"
URL="https://x.org/releases/individual/driver/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
	patch -p1 < $LAUNCHDIR/patches/rootless-ati.patch
	patch -p1 < $LAUNCHDIR/patches/link-failure.patch    
./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
