PACKAGE="graphviz"
VER="2.44.1"

DEPENDS=(   atk cairo expat fontconfig freetype-harfbuzz gc gcc gdk-pixbuf glib glibc gtk2 guile librsvg libtool libwebp libX11 libXrender pango zlib  )
CONFLICTS=()

URL="https://www2.graphviz.org/Packages/stable/portable_source/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	sed -i '/LIBPOSTFIX="64"/s/64//' configure.ac
	autoreconf -ivf
    ./configure $CONFIGUREOPTS --disable-perl --disable-php PS2PDF=true --with-webp
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}

pkg_postinstall(){
	dot -c
}
