PACKAGE="file"
VER="5.40"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Retrieves what does file contain"

DEPENDS=( glibc zlib xz bzip2 libseccomp   )
CONFLICTS=()

URL="ftp://ftp.astron.com/pub/file/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    mkdir build
    cd build
	./configure $CONFIGUREOPTS
	cd ..
}
__compilesrc(){
	cd build
    make FILE_COMPILE=$(pwd)/build/src/file $MAKEOPTS
    	cd ..
}
__installsrc(){
	cd build
    make $MAKEOPTS DESTDIR="$DEST" install
	cd ..
}
