PACKAGE="readline"
VER="8.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="GNU Text Interface library"

DEPENDS=(glibc ncurses)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/readline/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--with-curses \
	--disable-static \
	--enable-shared	
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
    sed -i 's/-lreadline/-lreadline -lncursesw/' $DEST/usr/lib/pkgconfig/readline.pc 
}
