PACKAGE="readline"
VER="8.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="GNU Text Interface library"

DEPENDS=(glibc ncurses)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/readline/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--with-curses	
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" SHLIB_LIBS="-lncursesw" install
}
