PACKAGE="binutils"
VER="2.37"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DESCRIPTION="GNU linker, assembler and other stuff"

DEPENDS=( glibc zlib elfutils flex gcc   )
CONFLICTS=()

URL="https://ftp.gnu.org/gnu/binutils/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS \
	--enable-gold	\
	--enable-ld=default	\
	--enable-plugins	\
	--with-system-zlib	\
	--enable-shared \
	--disable-werror \
	--enable-64-bit-bfd 
}
__compilesrc(){
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
mkdir -pv $DEST/usr/lib
install -vm755 libctf/.libs/libctf.so.0.0.0 $DEST/usr/lib
}
