PACKAGE="libinput"
VER="1.18.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Library for handling input devices"

DEPENDS=( libevdev mtdev eudev glibc   )
CONFLICTS=()

URL="https://github.com/wayland-project/libinput/archive/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${VER}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
	export DESTDIR="$DEST"
	meson \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--libexecdir=/usr/lib \
	-Ddebug-gui=false \
	-Ddocumentation=false \
	-Dtests=false \
	-Dlibwacom=false \
	-Dudev=true \
	. output
}
__compilesrc(){
	ninja -C output
}
__installsrc(){
	ninja -C output install
}
GITHUB_CHECK=1
