PACKAGE="pkg-config"
VER="0.29.2"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Properties of installed libraries"

DEPENDS=(glibc bash)
CONFLICTS=()

URL="https://pkg-config.freedesktop.org/releases/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--with-internal-glib	\
	--disable-host-tool
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
	mv $DEST/usr/bin/pkg-config $DEST/usr/bin/pkg-config-vanilla
cat >> $DEST/usr/bin/pkg-config <<EOF
#!/bin/bash
export PKG_CONFIG_PATH+="/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
exec pkg-config-vanilla \$@
EOF
	chmod -v +x $DEST/usr/bin/pkg-config
}
