PACKAGE="sowm"
VER="1.6"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Simple Stacked Window Manager by creator of neofetch"

DEPENDS=( libX11 glibc   )
CONFLICTS=()

URL="https://github.com/dylanaraps/sowm/archive/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${VER}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
#__preparesrc(){
    #./configure $CONFIGUREOPTS
#}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
