PACKAGE="libnsl"
VER="1.3.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Network Services library"

DEPENDS=(libtirpc)
CONFLICTS=()

URL="https://github.com/thkukuk/libnsl/releases/download/v${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
	./autogen.sh
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
