PACKAGE="autoconf"
VER="2.71"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"
 
DESCRIPTION="GNU Autoconf. Part of Autotools"

DEPENDS=( gawk m4 diffutils perl bash   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/autoconf/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
