PACKAGE="autoconf"
VER="2.69"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DEPENDS=(gawk m4 diffutils perl bash)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/autoconf/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
