PACKAGE="libsndfile"
VER="1.0.31"

DEPENDS=(   alsa-lib flac glibc libogg libvorbis opus  )
CONFLICTS=()

URL="https://github.com/libsndfile/libsndfile/releases/download/${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS --disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}

GITHUB_CHECK=y
