#!/bin/bash
PACKAGE="mkfontscale"
VER="1.2.1"

DESCRIPTION="Scale X11 fonts"

DEPENDS=(  )
CONFLICTS=()

URL="https://www.x.org/releases/individual/app/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}

__unpacksrc(){
	tar xf $SRCTGZ
}

__preparesrc(){
	./configure $CONFIGUREOPTS
}

__compilesrc(){
	make $MAKEOPTS
}

__installsrc(){
	make install DESTDIR="$DEST"
}
