PACKAGE="libXcursor"
VER="1.2.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 cursos extension"

DEPENDS=(libXfixes libXrender)
CONFLICTS=()

URL="https://x.org/releases/individual/lib/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
