PACKAGE="network-manager-applet"
VER="1.20.0"

DEPENDS=(   atk cairo gdk-pixbuf glib glibc gtk3 libnma libnotify libsecret ModemManager NetworkManager pango  )
CONFLICTS=()

URL="https://download.gnome.org/sources/${PACKAGE}/1.20/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	mkdir build
	cd build
	export DESTDIR="$DEST"
	meson --prefix=/usr \
		-Dappindicator=no \
		-Dselinux=false \
		-Dteam=false ..
	cd ..
}
__compilesrc(){
	cd build
	ninja
	cd ..
}
__installsrc(){
	cd build
	ninja install
}
