#!/bin/bash
PACKAGE="libnl"
VER="3.5.0"

DESCRIPTION="Netlink library"

DEPENDS=(  )
CONFLICTS=()

URL="https://github.com/thom311/libnl/releases/download/libnl3_5_0/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}

__unpacksrc(){
	tar xf $SRCTGZ
}

__preparesrc(){
	./configure $CONFIGUREOPTS --disable-static
}

__compilesrc(){
	make $MAKEOPTS
}

__installsrc(){
	make install DESTDIR="$DEST"
}
