PACKAGE="libgpg-error"
VER="1.42"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Library for handling gpg errors"

DEPENDS=( glibc bash   )
CONFLICTS=()

URL="https://www.gnupg.org/ftp/gcrypt/libgpg-error/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
