PACKAGE="psmisc"
VER="23.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Small /proc fs programs"

DEPENDS=( ncurses glibc   )
CONFLICTS=()

URL=" https://sourceforge.net/projects/psmisc/files/psmisc/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
