PACKAGE="attr"
VER="2.4.48"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(glibc)
CONFLICTS=()

URL="http://download.savannah.gnu.org/releases/attr/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	tar xzf $SRCTGZ 
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
