PACKAGE="bison"
VER="3.8.2"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DESCRIPTION="Modern yacc"

DEPENDS=( glibc m4 bash gettext   )
DEPENDS=( glibc m4 bash gettext   )
DEPENDS=( glibc m4 bash gettext   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/bison/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
