PACKAGE="libevent"
VER="2.1.12"

DEPENDS=(   glibc openssl  )
CONFLICTS=()

URL="https://github.com/libevent/libevent/releases/download/release-${VER}-stable/"
SRCDIR="${PACKAGE}-${VER}-stable"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS --disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=y
