PACKAGE="diffutils"
VER="3.8"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DESCRIPTION="Create patches"

DEPENDS=( glibc bash   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/diffutils/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
}
