PACKAGE="pcre"
VER="8.45"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=()
CONFLICTS=()

DESCRIPTION="Perl Compatible Regular Expressions"

URL="https://ftp.pcre.org/pub/pcre/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	  --docdir=/usr/share/doc/pcre-8.44 \
            --enable-unicode-properties       \
            --enable-pcre16                   \
            --enable-pcre32                   \
            --enable-pcregrep-libz            \
            --enable-pcregrep-libbz2          \
            --enable-pcretest-libreadline     \
            --disable-static 
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
