PACKAGE="xorg-iceauth"
VER="1.0.8"

DEPENDS=(   glibc libICE  )
CONFLICTS=()

URL="https://xorg.freedesktop.org/archive/individual/app/"
SRCDIR="${PACKAGE/xorg-/}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
