PACKAGE="xsetroot"
VER="1.1.2"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(libXmu libXrender libXfixes libXcursor xbitmaps)
CONFLICTS=()

URL="https://x.org/archive//individual/app/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--mandir=/usr/share/man \
	--localstatedir=/var
}
__compilesrc(){
    make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
