PACKAGE="python"
VER="3.8.5"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Python3 interpreted general-purpose programing language"

DEPENDS=( bzip2 expat gdbm libffi openssl zlib glibc libnsl libtirpc libxcrypt ncurses readline sqlite3 util-linux xz   )
CONFLICTS=()

URL="https://www.python.org/ftp/python/${VER}/"
SRCDIR="Python-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--enable-shared	\
	--with-ensurepip	\
	--with-system-expat	\
	--with-system-ffi
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
    ln -sfv python3 $DEST/usr/bin/python
}
