#!/bin/bash
PACKAGE="wpa_supplicant"
VER="2.9"

DESCRIPTION="WPA Auth daemon"

DEPENDS=( glibc libnl ncurses openssl readline  dbus  )
CONFLICTS=()

URL="https://w1.fi/releases/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}

__unpacksrc(){
	tar xf $SRCTGZ
}

__preparesrc(){
cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CONFIG_CTRL_IFACE=y
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
CFLAGS += -I/usr/include/libnl3
EOF
}

__compilesrc(){
	cd wpa_supplicant
	make BINDIR=/sbin LIBDIR=/lib $MAKEOPTS
}

__installsrc(){
	mkdir -pv $DEST/sbin $DEST/usr/share/man/man{5,8} $DEST/usr/share/dbus-1/{system.d,system-services}
install -v -m755 wpa_{cli,passphrase,supplicant} $DEST/sbin/ &&
install -v -m644 dbus/fi.w1.wpa_supplicant1.service $DEST/usr/share/dbus-1/system-services/fi.w1.wpa_supplicant1.service &&
install -v -m644 dbus/dbus-wpa_supplicant.conf $DEST/usr/share/dbus-1/system.d/wpa_supplicant.conf
install -v -m644 doc/docbook/wpa_supplicant.conf.5 $DEST/usr/share/man/man5/ &&
install -v -m644 doc/docbook/wpa_{cli,passphrase,supplicant}.8 $DEST/usr/share/man/man8/
}
