PACKAGE="mtdev"
VER="1.1.6"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Multitouch Protocol Translation library"

DEPENDS=( glibc   )
CONFLICTS=()

URL="https://bitmath.org/code/mtdev/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
