PACKAGE="lvm2"
VER="2.03.10"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Logical Volume Manager"

DEPENDS=( eudev glibc libaio ncurses readline util-linux   )
CONFLICTS=()

URL="https://sourceware.org/ftp/lvm2/"
SRCDIR="LVM2.${VER}"
SRCTGZ="${SRCDIR}.tgz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--exec-prefix=	\
	--enable-cmdlib	\
	--enable-pkgconfig	\
	--enable-udev_sync

}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
