PACKAGE="mupdf"
VER="1.19.0"

DEPENDS=(   curl freetype-harfbuzz glibc libjpeg-turbo libX11 libXext libXrandr mesa openssl zlib  )
CONFLICTS=()

URL="http://www.mupdf.com/downloads/archive/"
SRCDIR="${PACKAGE}-${VER}-source"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
sed -i '/MU.*_EXE. :/{
        s/\(.(MUPDF_LIB)\)\(.*\)$/\2 | \1/
        N
        s/$/ -lmupdf -L$(OUT)/
        }' Makefile
cat > user.make << EOF
USE_SYSTEM_FREETYPE := yes
USE_SYSTEM_HARFBUZZ := yes
USE_SYSTEM_JBIG2DEC := no
USE_SYSTEM_JPEGXR := no # not used without HAVE_JPEGXR
USE_SYSTEM_LCMS2 := no # need lcms2-art fork
USE_SYSTEM_LIBJPEG := yes
USE_SYSTEM_MUJS := no # build needs source anyways
USE_SYSTEM_OPENJPEG := no
USE_SYSTEM_ZLIB := yes
USE_SYSTEM_GLUT := no # need freeglut2-art fork
USE_SYSTEM_CURL := yes
USE_SYSTEM_GUMBO := no
EOF
}
__compilesrc(){
	export XCFLAGS=-fpic
    make $MAKEOPTS build=release shared=yes
}
__installsrc(){
    make $MAKEOPTS prefix="$DEST/usr" install shared=yes &&
	    chmod 755 $DEST/usr/lib/libmupdf.so &&
	    ln -sv mupdf-x11 $DEST/usr/bin/mupdf
}
