PACKAGE="gdbm"
VER="1.21"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=( bash glibc ncurses readline   )
CONFLICTS=()

DESCRIPTION="GNU Database Manager"

URL="http://ftp.gnu.org/gnu/gdbm/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--enable-libgdbm-compat --disable-static 
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
