PACKAGE="libgdata"
VER="0.18.1"

DEPENDS=(  )
CONFLICTS=()

URL="https://download.gnome.org/sources/libgdata/0.18/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	mkdir build
	cd build
	export DESTDIR="$DEST"
	meson --prefix=/usr ..
	cd ..
}
__compilesrc(){
	cd build
	ninja
	cd ..
}
__installsrc(){
	cd build
	ninja install
}
