PACKAGE="libxcb"
VER="1.14"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 bindings for C"

DEPENDS=(libXau xcb-proto xorg-util-macros)
CONFLICTS=()

URL="https://xorg.freedesktop.org/archive/individual/lib/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    sed -i 's/pthread-stubs //' configure
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
