PACKAGE="sed"
VER="4.8"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Stream-oriented ED(itor)"

DEPENDS=( glibc acl attr   )
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/sed/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
