PACKAGE="xorg-util-macros"
VER="1.19.2"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=()
CONFLICTS=()

URL="https://x.org/releases/individual/util/"
SRCDIR="${PACKAGE#xorg-}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
