PACKAGE="meson"
VER="0.58.2"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="build system"

DEPENDS=( python ninja   )
CONFLICTS=()

URL="https://github.com/mesonbuild/meson/releases/download/${VER/.rc2/}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    #./configure $CONFIGUREOPTS
    true
}
__compilesrc(){
    #make $MAKEOPTS
    python setup.py build
}
__installsrc(){
    #make $MAKEOPTS DESTDIR="$DEST" install
    python setup.py install --prefix usr --root $DEST
}
GITHUB_CHECK=1
