PACKAGE="make"
VER="4.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(glibc guile)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/make/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS --without-guile
}
__compilesrc(){
    make $MAKEOPTS #CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
