PACKAGE="libpng"
VER="1.6.37"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(zlib)
CONFLICTS=()

URL="https://github.com/glennrp/libpng/archive/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="v${VER}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
