PACKAGE="coreutils"
VER="8.32"

ARCH="installer"
ACCESS="restricted"

DEPENDS=(glibc acl attr gmp libcap openssl)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/coreutils/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
CRYPT="key"

__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
	make $MAKEOPTS DESTDIR="$DEST" install
}
