PACKAGE="coreutils"
VER="8.32"

ARCH="installer"
ACCESS="restricted"

DEPENDS=(glibc acl attr gmp libcap openssl)
CONFLICTS=()

DESCRIPTION="Core utilities, supposed to be installed on every system"

URL="http://ftp.gnu.org/gnu/coreutils/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"
CRYPT="key"

__getsrc(){
	wget -q $SRCURL
}
__unpacksrc(){
	tar xJf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS
}
__compilesrc(){
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR="$DEST" install
}
