PACKAGE="hicolor-icon-theme"
VER="0.17"

DEPENDS=(  )
CONFLICTS=()

URL="https://icon-theme.freedesktop.org/releases/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
