PACKAGE="gmp"
VER="6.2.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="GNU MultiProcessing library"

DEPENDS=(gcc bash)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/gmp/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    	cp -v configfsf.guess config.guess
	cp -v configfsf.sub   config.sub
	./configure $CONFIGUREOPTS	\
	--enable-cxx	\
	--disable-static
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
