PACKAGE="gmp"
VER="6.2.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(gcc bash)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/gmp/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS	\
	--enable-cxx	
}
__compilesrc(){
    make $MAKEOPTS CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS"
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
