PACKAGE="tar"
VER="1.32"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(glibc acl attr)
CONFLICTS=()

DESCRIPTION="Tape archiver"

URL="http://ftp.gnu.org/gnu/tar/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
