PACKAGE="cbindgen"
VER="0.20.0"

DEPENDS=(   gcc glibc  )
CONFLICTS=()

URL="https://github.com/eqrion/cbindgen/archive/v${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__compilesrc(){
	cargo build --release
}
__installsrc(){
	mkdir -pv $DEST/usr/bin
	install -vm755 target/release/cbindgen $DEST/usr/bin/
}
GITHUB_CHECK=y
