PACKAGE="fribidi"
VER="1.0.9"

DEPENDS=(   glibc  )
CONFLICTS=()

URL="https://github.com/fribidi/fribidi/releases/download/v${VER}/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xf $SRCTGZ
}
__preparesrc(){
	mkdir build
	cd build
	export DESTDIR="$DEST"
	meson --prefix=/usr ..
	cd ..
}
__compilesrc(){
	cd build
	ninja
	cd ..
}
__installsrc(){
	cd build
	ninja install
}
