PACKAGE="dwm"
VER="6.2"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Dynamic Window Manager by suckless.org"

DEPENDS=()
CONFLICTS=()

URL="https://dl.suckless.org/dwm/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
#__preparesrc(){
#    ./configure $CONFIGUREOPTS
#}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
