PACKAGE="gzip"
VER="1.10"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="GNU DEFLATE Compressor"

DEPENDS=(glibc bash less)
CONFLICTS=()

URL="http://ftp.gnu.org/gnu/gzip/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
