PACKAGE="pixman"
VER="0.40.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Low-level software library for pixel manipulation"

DEPENDS=( glibc   )
CONFLICTS=()

URL="https://x.org/releases/individual/lib/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--disable-gtk
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
