PACKAGE="sysklogd"
VER="1.5.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="Daemons and Kernel logging utility"

DEPENDS=()
CONFLICTS=()

URL="http://www.infodrom.org/projects/sysklogd/download/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    #./configure $CONFIGUREOPTS
    sed -i 's/union wait status/int status/' syslogd.c
    true
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    mkdir -p $DEST/sbin $DEST/usr/share/man/man8
    make $MAKEOPTS prefix="$DEST" BINDIR="$DEST/sbin" install --ignore-errors
}
