PACKAGE="libnghttp2"
VER="1.45.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="next-gen HTTP/2 library"

DEPENDS=( glibc  elogind gcc jansson libxml2 openssl zlib  )
CONFLICTS=()

URL="https://github.com/nghttp2/nghttp2/releases/download/v${VER}/"
SRCDIR="nghttp2-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
