PACKAGE="dhcpcd"
VER="9.3.4"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="DHCP Daemon"

DEPENDS=(bash glibc eudev)
CONFLICTS=()

URL="https://roy.marples.name/downloads/dhcpcd/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
