PACKAGE="mesa"
VER="21.2.3"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="OpenGL & Vulkan implementation"

DEPENDS=( expat libX11 libXdamage libXext libXrandr libXrender libXxf86vm libdrm libxcb libxshmfence llvm xorgproto zlib elfutils gcc glibc libunwind libXfixes zstd  wayland  )
CONFLICTS=()

URL="https://archive.mesa3d.org/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    curl -LO $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
	export DESTDIR="$DEST"
	meson \
	--prefix=/usr \
	--mandir=/usr/share/man \
	--localstatedir=/var \
	--buildtype=release \
	-Dplatforms=x11,wayland \
	-Ddri3=enabled \
	-Degl=enabled \
	-Dgallium-va=enabled \
	-Dgallium-vdpau=enabled \
	-Dgbm=enabled \
	-Dglx=dri \
	-Dosmesa=true \
	. output
}
__compilesrc(){
	ninja -C output
}
__installsrc(){
	ninja -C output install
}
