PACKAGE="pam"
VER="1.5.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(audit)
CONFLICTS=()

DESCRIPTION="Pluggable Authentication Modules"

URL="https://github.com/linux-pam/linux-pam/releases/download/v${VER}/"
SRCDIR="Linux-PAM-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./autogen.sh
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
GITHUB_CHECK=1
