PACKAGE="bash"
VER="5.0"

ACCESS="restricted"
ARCH="installer"
CRYPT="key"

DEPENDS=(readline glibc ncurses)
CONFLICTS=()

DESCRIPTION="Bourne-Again SHell"

URL="https://ftp.gnu.org/gnu/bash/"
SRCTGZ="${PACKAGE}-${VER}.tar.gz"
SRCDIR="${PACKAGE}-${VER}"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
	wget -c $SRCURL
}
__unpacksrc(){
	tar xzf $SRCTGZ
}
__preparesrc(){
	./configure $CONFIGUREOPTS	\
	--without-bash-malloc	\
	--with-installed-readline \
	--with-curses \
	--enable-job-control
}
__compilesrc(){
	sed -i 's/-lcurses/-lncursesw/' Makefile
	make $MAKEOPTS
}
__installsrc(){
	make $MAKEOPTS DESTDIR=$DEST install
	mkdir -p $DEST/bin
	mv $DEST/usr/bin/bash $DEST/bin/bash
	pushd $DEST
	ln -s /bin/bash bin/sh
	ln -s /bin/bash usr/bin/bash
	ln -s /bin/bash usr/bin/sh
	popd
}
