PACKAGE="sqlite3"
VER="3.33.0"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DEPENDS=(readline zlib)
CONFLICTS=()

DESCRIPTION="sqlite3 database"

URL="https://www.sqlite.org/2020/"
SRCDIR="sqlite-autoconf-3330000"
SRCTGZ="${SRCDIR}.tar.gz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
