PACKAGE="libXrender"
VER="0.9.10"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="X11 Rendering"

DEPENDS=()
CONFLICTS=()

URL="https://x.org/releases/individual/lib/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.bz2"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xjf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
