PACKAGE="libldap"
VER="2.4.56"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="LDAP protocol library"

DEPENDS=(libsasl)
CONFLICTS=()

URL="http://mirror.eu.oneandone.net/software/openldap/openldap-release/"
SRCDIR="openldap-${VER}"
SRCTGZ="${SRCDIR}.tgz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -q $SRCURL
}
__unpacksrc(){
    tar xzf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--disable-debug	\
	--enable-shared
    make depend
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make DESTDIR="$DEST" install
}
