PACKAGE="curl"
VER="7.79.1"

ARCH="installer"
ACCESS="restricted"
CRYPT="key"

DESCRIPTION="CURL Downloader"

DEPENDS=( krb5 libssh2 libpsl libnghttp2 libidn2 brotli glibc openssl zlib zstd  libldap  )
CONFLICTS=()

URL="https://curl.se/download/"
SRCDIR="${PACKAGE}-${VER}"
SRCTGZ="${SRCDIR}.tar.xz"
SRCURL="${URL}${SRCTGZ}"

__getsrc(){
    wget -c $SRCURL
}
__unpacksrc(){
    tar xJf $SRCTGZ
}
__preparesrc(){
    ./configure $CONFIGUREOPTS \
	--without-librtmp --with-openssl
}
__compilesrc(){
    make $MAKEOPTS
}
__installsrc(){
    make $MAKEOPTS DESTDIR="$DEST" install
}
